require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PassagesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Passage. As you add validations to Passage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PassagesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all passages as @passages" do
      passage = Passage.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:passages)).to eq([passage])
    end
  end

  describe "GET show" do
    it "assigns the requested passage as @passage" do
      passage = Passage.create! valid_attributes
      get :show, {:id => passage.to_param}, valid_session
      expect(assigns(:passage)).to eq(passage)
    end
  end

  describe "GET new" do
    it "assigns a new passage as @passage" do
      get :new, {}, valid_session
      expect(assigns(:passage)).to be_a_new(Passage)
    end
  end

  describe "GET edit" do
    it "assigns the requested passage as @passage" do
      passage = Passage.create! valid_attributes
      get :edit, {:id => passage.to_param}, valid_session
      expect(assigns(:passage)).to eq(passage)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Passage" do
        expect {
          post :create, {:passage => valid_attributes}, valid_session
        }.to change(Passage, :count).by(1)
      end

      it "assigns a newly created passage as @passage" do
        post :create, {:passage => valid_attributes}, valid_session
        expect(assigns(:passage)).to be_a(Passage)
        expect(assigns(:passage)).to be_persisted
      end

      it "redirects to the created passage" do
        post :create, {:passage => valid_attributes}, valid_session
        expect(response).to redirect_to(Passage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved passage as @passage" do
        post :create, {:passage => invalid_attributes}, valid_session
        expect(assigns(:passage)).to be_a_new(Passage)
      end

      it "re-renders the 'new' template" do
        post :create, {:passage => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested passage" do
        passage = Passage.create! valid_attributes
        put :update, {:id => passage.to_param, :passage => new_attributes}, valid_session
        passage.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested passage as @passage" do
        passage = Passage.create! valid_attributes
        put :update, {:id => passage.to_param, :passage => valid_attributes}, valid_session
        expect(assigns(:passage)).to eq(passage)
      end

      it "redirects to the passage" do
        passage = Passage.create! valid_attributes
        put :update, {:id => passage.to_param, :passage => valid_attributes}, valid_session
        expect(response).to redirect_to(passage)
      end
    end

    describe "with invalid params" do
      it "assigns the passage as @passage" do
        passage = Passage.create! valid_attributes
        put :update, {:id => passage.to_param, :passage => invalid_attributes}, valid_session
        expect(assigns(:passage)).to eq(passage)
      end

      it "re-renders the 'edit' template" do
        passage = Passage.create! valid_attributes
        put :update, {:id => passage.to_param, :passage => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested passage" do
      passage = Passage.create! valid_attributes
      expect {
        delete :destroy, {:id => passage.to_param}, valid_session
      }.to change(Passage, :count).by(-1)
    end

    it "redirects to the passages list" do
      passage = Passage.create! valid_attributes
      delete :destroy, {:id => passage.to_param}, valid_session
      expect(response).to redirect_to(passages_url)
    end
  end

end
